import "./style/banner.scss";
import "destyle.css/destyle.css";
// import 'selectize/dist/css/selectize.css';
import 'nouislider/dist/nouislider.css';
// import 'swiper/swiper-bundle.css';
import 'photoswipe/style.css';

import "./style/fonts.scss";
import "./style/common.scss";
import "./style/typography.scss";

import "./style/blocks/btn.scss";
import "./style/blocks/checkbox.scss";
import "./style/blocks/chip.scss";
import "./style/blocks/file.scss";
import "./style/blocks/input.scss";
import "./style/blocks/pages.scss";
import "./style/blocks/photoswipe.scss";
import "./style/blocks/radio.scss";
import "./style/blocks/select.scss";
import "./style/blocks/wpcf7.scss";
import "./style/blocks/form.scss";
import "./style/blocks/simplebar.scss";

import './modules/header/header.scss';
import './modules/footer/footer.scss';
import './modules/hero/hero.scss';
import './modules/welcome/welcome.scss';
import './modules/ceo/ceo.scss';
import './modules/directions/directions.scss';
import './modules/map/map.scss';
import './modules/clients/clients.scss';
import './modules/partners/partners.scss';
import './modules/banner/banner.scss';
import './modules/cards/cards.scss';
import './modules/services/services.scss';
import './modules/steps/steps.scss';
import './modules/faq/faq.scss';
import './modules/vacancies/vacancies.scss';
import './modules/head/head.scss';
import './modules/breadcrumbs/breadcrumbs.scss';
import './modules/vacancy/vacancy.scss';
import './modules/newsList/newsList.scss';
import './modules/news/news.scss';
import './modules/gallery/gallery.scss';
import './modules/clientsList/clientsList.scss';
import './modules/regalia/regalia.scss';
import './modules/notFound/notFound.scss';
import './modules/sbg/sbg.scss';
import './modules/tabs/tabs.scss';
import './modules/audit360/audit360.scss';
import './modules/cta/cta.scss';
import './modules/realize/realize.scss';
import './modules/profile/profile.scss';
import './modules/img/img.scss';
import './modules/methods/methods.scss';
import './modules/popup/popup.scss';
